[package]
name = "r3bl_rs_utils"
description = "Async Redux library, TUI utilities, and useful data structures"
# At most 5 keywords w/ no spaces, each has max length of 20 char.
keywords = ["tui", "color", "terminal", "redux", "non-binary-tree"]
categories = ["algorithms", "data-structures"]
# When you change this, make sure to update `README.md` as well.
version = "0.7.35"
edition = "2021"
readme = "README.md" # This is not included in cargo docs.
# Email address(es) has to be verified at https://crates.io/me/
authors = ["Nazmul Idris <idris@developerlife.com>"]
repository = "https://github.com/r3bl-org/r3bl-rs-utils"
documentation = "https://docs.rs/r3bl_rs_utils"
homepage = "https://r3bl.com"
license = "Apache-2.0"

[lib]
name = "r3bl_rs_utils"
path = "src/lib.rs"

# Documentation for crate layout.
# [General crate layout](https://stackoverflow.com/a/57767413/2085356)
# [Nesting crates for procedural macros](https://stackoverflow.com/a/64288799/2085356)

[dependencies]

# r3bl_rs_utils
r3bl_rs_utils_core = { version = "0.7.10", path = "core" }
r3bl_rs_utils_macro = { version = "0.7.6", path = "macro" }

# Logging
log = "0.4.16"
simplelog = "0.12.0"

# Time
chrono = "0.4.0"
time = "0.3.9"

# Misc
rand = "0.8.4"

# Terminal
ansi_term = "0.12.1"
atty = "0.2.14"

# Async
tokio = { version = "1.17.0", features = ["full"] }
async-trait = "0.1.53"
futures = "0.3.21"

[workspace]
members = ["macro", "core"]
