[package]
name = "r3bl_rs_utils"
description = "Rust language utilities inspired by Kotlin scope functions, TUI utilities, and useful data structures"
# At most 5 keywords w/ no spaces, each has max length of 20 char.
keywords = ["tui", "color", "terminal", "redux", "non-binary-tree"]
categories = ["algorithms", "data-structures"]
# When you change this, make sure to update `README.md` as well.
version = "0.6.6"
edition = "2021"
license = "Apache-2.0"
readme = "README.md" # This is not included in cargo docs.
# Email address(es) has to be verified at https://crates.io/me/
authors = ["Nazmul Idris <idris@developerlife.com>"]
repository = "https://github.com/r3bl-org/r3bl-rs-utils"
documentation = "https://docs.rs/r3bl_rs_utils"
homepage = "https://r3bl.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://stackoverflow.com/a/57767413/2085356

[lib]
name = "r3bl_rs_utils"
path = "src/lib.rs"

[dependencies]

rand = "0.8.4"
ansi_term = "0.12.1"
chrono = "0.4.0"
atty = "0.2.14"
tokio = { version = "1", features = ["full"] }
